"""empty message

Revision ID: d564ad3179bc
Revises: 
Create Date: 2019-04-16 23:48:46.175146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd564ad3179bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=14), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
